### ISSUE TITLE
sh run_stage0.sh

### ISSUE THREAD

**Issue by 2085924055** [Freedomcls/NeRF-VPT#2]
when I run the following commond:
python train.py --dataset_name replica --root_dir ./room_0/Sequence_1/ --N_importance 64 --img_wh 320 240 --nu
m_epochs 18 --batch_size 2048 --optimizer adam --lr 0.0005 --lr_scheduler steplr --decay_step 4 8 --decay_gamma 0.5 --exp_name replica_stage0 --loss_type mse --chunk 40000 --nerf_model NeRF --num_gpus 1

I get this error:
Traceback (most recent call last):
  File "E:\pycode\NeRF-VPT-main\train.py", line 70, in <module>
    trainer.fit(system)
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 513, in fit
    self.dispatch()
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 553, in dispatch
    self.accelerator.start_training(self)
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 676, in run_train
    self.train_loop.on_train_end()
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 134, in on_train_end
    self.check_checkpoint_callback(should_update=True, is_last=True)
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 164, in check_checkpoint_callback
    cb.on_validation_end(self.trainer, model)
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 212, in on_validation_end
    self.save_checkpoint(trainer, pl_module)
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 259, in save_checkpoint
    self._save_top_k_checkpoints(trainer, pl_module, monitor_candidates)
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 567, in _save_top_k_checkpoints       
    self._update_best_and_save(current, epoch, step, trainer, pl_module, metrics)
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 609, in _update_best_and_save
    self._save_model(filepath, trainer, pl_module)
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 331, in _save_model
    self._fs.makedirs(os.path.dirname(filepath), exist_ok=True)
  File "D:\anaconda\envs\NeRF-VPT\lib\site-packages\fsspec\implementations\local.py", line 53, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "D:\anaconda\envs\NeRF-VPT\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] 目录名称无效。: 'ckpts/replica_stage0\\{epoch:d}'
Epoch 0: 100%|██████████| 6930/6930 [32:41<00:00,  3.53it/s, loss=0.00587, v_num=7, train_psnr=26.30, val_loss=0.0059, val_psnr=26.50]

The problem seems to be due to a problem with the path somewhere, but I have checked that the path is not wrong. I don't understand why the path is invalid.
Has anyone had this problem？

**Comment by Freedomcls** [comment]
Hello, perhaps you can try to create a "ckpt" folder in the main directory.

**Comment by 2085924055** [comment]
hi, "ckpt" folder already exists and ckpts/replica_stage0 path exists. It seems to be because of '{epoch:d}' in the following code：
checkpoint_callback = ModelCheckpoint(dirpath=os.path.join(f'ckpts/{hparams.exp_name}',
                                                             '{epoch:d}'),
                                       monitor='val/loss',
                                       mode='min',
                                      save_top_k=100,)
                                      
I'm using windows to run this code. '{epoch:d}' seems to be a dynamic string that runs in linux, which does not run in windows. I have changed the above code to the following form：
checkpoint_callback = ModelCheckpoint(dirpath=f'ckpts/{hparams.exp_name}/',  
        filename='{epoch}',  
        save_top_k=100,
        monitor='val_loss',
        mode='min',
    )
Now run_stage0.sh can run. I have another question. 
run_stage0_render.sh file command ckpts/replica_stage0/\{epoch\:d\}/epoch\=17-step\=15191.ckpt. how to modify the path of ckpt to adapt to windows. I don't understand ckpts/replica_stage0/\{epoch\:d\}/epoch\=17-step\=15191.ckpt . What does epoch\=17-step\=15191.ckpt mean?
